# Exercise 1.C Performing operations on arrays

In [28]:
import numpy as np

# sample arrays

In [29]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)


TypeError: 'tuple' object is not callable

# permutations


In [5]:
print(r_4)

[[34 73 21 21 74]
 [51 55 39 56 71]
 [72 65 36 25 77]
 [56 54 43 52 55]]


In [9]:
np.random.shuffle(r_4)
print(r_4)

[[56 54 43 52 55]
 [34 73 21 21 74]
 [72 65 36 25 77]
 [51 55 39 56 71]]


In [26]:
np.random.shuffle(r_4)
print(r_4)

TypeError: 'tuple' object is not callable

In [ ]:

#The shuffle function rearranges the rows of the array.
#It does not mix every number individually only the order of rows changes


In [25]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print()
print(r_4)

TypeError: 'tuple' object is not callable

In [ ]:
# when you want to shuffle the info but not change the original input

## Mathematical Operations. 

In [23]:
print(r_1)
print(r_2)

TypeError: 'tuple' object is not callable

In [24]:

print(r_1, r_1.shape)
print(r_3, r_3.shape)

result = np.add(r_1, r_3)
print(result)
print(result.shape)


TypeError: 'tuple' object is not callable