# Exercise 1.C Performing operation


In [2]:
import numpy as np

## Sample Arrays

In [3]:

# Creating random arrays (same as Exercise 1B)
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.rand(4, 5)

print(r_1, r_2, r_3, r_4, r_5)


[20 20] [[ 8 14]] [[0.03964692]
 [0.37079357]] [[34 66 43 55 53]
 [39 20 45 59 87]
 [35 79 45 74 74]
 [46 91 83 98 43]] [[0.46833063 0.89039154 0.13596889 0.3116088  0.61787057]
 [0.2492182  0.76375144 0.86448695 0.22704448 0.28347717]
 [0.80102618 0.87797484 0.21799371 0.15197986 0.5420632 ]
 [0.50135189 0.09439534 0.94483653 0.8985755  0.63617567]]


In [4]:

## Permutations


In [5]:
print(r_4)

[[34 66 43 55 53]
 [39 20 45 59 87]
 [35 79 45 74 74]
 [46 91 83 98 43]]


In [6]:

np.random.shuffle(r_4)
print(r_4)


[[34 66 43 55 53]
 [35 79 45 74 74]
 [46 91 83 98 43]
 [39 20 45 59 87]]


In [7]:
# it does not mix individual values across the entire array, only the order of rows changes.

In [8]:

new_shuffle = np.random.permutation(r_4)

print(new_shuffle)
print(r_4)


[[35 79 45 74 74]
 [39 20 45 59 87]
 [34 66 43 55 53]
 [46 91 83 98 43]]
[[34 66 43 55 53]
 [35 79 45 74 74]
 [46 91 83 98 43]
 [39 20 45 59 87]]


In [9]:
# Permutation is used when you want a shuffled copy without changing the original

In [10]:
print(r_1, r_1.shape)
print(r_2, r_2.shape)

result = np.add(r_1, r_2)
print(result)
print(result.shape)

[20 20] (2,)
[[ 8 14]] (1, 2)
[[28 34]]
(1, 2)


In [11]:
print(r_1, r_1.shape)
print(r_3, r_3.shape) 

result= np.add(r_1, r_3)
print(result)
print(result.shape)

[20 20] (2,)
[[0.03964692]
 [0.37079357]] (2, 1)
[[20.03964692 20.03964692]
 [20.37079357 20.37079357]]
(2, 2)


In [12]:
print(r_2, r_2.shape)
print(r_4, r_4.shape) 

result= np.add(r_2, r_4)
print(result)
print(result.shape)

[[ 8 14]] (1, 2)
[[34 66 43 55 53]
 [35 79 45 74 74]
 [46 91 83 98 43]
 [39 20 45 59 87]] (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [15]:
print(np.add(r_1, r_4))
except Exception as e:
    print(e)



SyntaxError: invalid syntax (3260008863.py, line 2)

In [14]:

print(r_4 + np.array([1]))
print(r_4 + np.array([[1]]))
print(r_4 + np.array([1,1,1,1,1]))


[[35 67 44 56 54]
 [36 80 46 75 75]
 [47 92 84 99 44]
 [40 21 46 60 88]]
[[35 67 44 56 54]
 [36 80 46 75 75]
 [47 92 84 99 44]
 [40 21 46 60 88]]
[[35 67 44 56 54]
 [36 80 46 75 75]
 [47 92 84 99 44]
 [40 21 46 60 88]]


In [21]:
try:
    print(r_4 + np.array([[1],[1]]))
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (4,5) (2,1) 


# broadcasting allows arrays of a different size by expanding the smaller array

## Rounding

In [23]:
print(r_3)

[[0.03964692]
 [0.37079357]]


In [24]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [25]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [26]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [28]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [30]:
print(np.round(r_3, 2))

[[0.04]
 [0.37]]


## Cumulative Operations

In [32]:
print(r_4)

[[34 66 43 55 53]
 [35 79 45 74 74]
 [46 91 83 98 43]
 [39 20 45 59 87]]


In [33]:
print(np.sum(r_4)) 

1169


print(np.sum(r_4, axis=0))

In [35]:
print(np.sum(r_4, axis=1))

[251 307 361 250]


In [36]:
print(np.cumsum(r_4))

[  34  100  143  198  251  286  365  410  484  558  604  695  778  876
  919  958  978 1023 1082 1169]


In [37]:
print(np.cumsum(r_4, axis=0))

[[ 34  66  43  55  53]
 [ 69 145  88 129 127]
 [115 236 171 227 170]
 [154 256 216 286 257]]


## Grocery Problem

In [39]:
# Order: vegetables, fruits, snacks, beverages
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)


[2 3 4 0]
[4 0 1 2]


In [41]:
print(f"the first bag has {np.sum(bag1)} items, and the second one has {np.sum(bag2)} items.")

the first bag has 9 items, and the second one has 7 items.


In [42]:
totals = bag1+bag2
print(f"There are {totals[0]} vegtables, {totals[1]} fruits,{totals[2]} boxes of snacks, and {totals[3]} beverages.")

There are 6 vegtables, 3 fruits,5 boxes of snacks, and 2 beverages.


## Teamwork

In [43]:
ali = np.array([5,4,6,4,2])
ben = np.array([0,5,5,3,4])   # missed Monday
carla = np.array([3,6,0,3,4]) # missed Wednesday


In [44]:

all_knocks = np.array([ali, ben, carla])
print(all_knocks)


[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [45]:

print(np.sum(all_knocks, axis=1))  # per person
print(np.sum(all_knocks))          # total group


[21 17 16]
54


In [46]:

daily_totals = np.sum(all_knocks, axis=0)
rolling_total = np.cumsum(daily_totals)

estimated_votes = rolling_total * 0.5
print(estimated_votes)


[ 4.  11.5 17.  22.  27. ]
